import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { HomeLabels, HomeLinks } from "@/constants/constant";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>{HomeLabels.teamName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href={HomeLinks.brandSite}
              target="_blank"
              rel="noopener noreferrer"
            >
              {HomeLabels.teamName}
            </a>
          </div>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/logo.png"
            alt="Logo"
            width={414}
            height={67}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {HomeLabels.headingSecondaryOne} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {HomeLabels.subHeadingSecondaryOne}
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {HomeLabels.headingSecondaryTwo} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {HomeLabels.subHeadingSecondaryTwo}
            </p>
          </a>

          <a href={HomeLinks.secondaryRoute} className={styles.card}>
            <h2 className={inter.className}>
              {HomeLabels.headingSecondaryThree} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {HomeLabels.subHeadingSecondaryThree}
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              {HomeLabels.headingSecondaryFour} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {HomeLabels.subHeadingSecondaryFour}
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
